name: teams-for-linux-julian
version: '0.2.1'
summary: Unofficial Microsoft Teams client for Linux
description: |
  Unofficial Microsoft Teams client for Linux using Electron. 
  It uses the Web App and wraps it as a standalone application using Electron.
base: core18
grade: stable
confinement: strict

# plugs:
#   gnome-3-26-1604:
#     interface: content
#     target: $SNAP/gnome-platform
#     default-provider: gnome-3-26-1604
#   gtk-3-themes:
#     interface: content
#     target: $SNAP/data-dir/themes
#     default-provider: gtk-common-themes
#   icon-themes:
#     interface: content
#     target: $SNAP/data-dir/icons
#     default-provider: gtk-common-themes
#   sound-themes:
#     interface: content
#     target: $SNAP/data-dir/sounds
#     default-provider: gtk-common-themes

parts:
  teams-for-linux:
    # See 'snapcraft plugins'
    plugin: nodejs
    # node-engine: 8.12.0
    # node-package-manager: yarn
    source: .
    # stage-packages:
    #   - libasound2
    #   - libgconf2-4
    #   - libnspr4
    #   - libnss3
    #   - libxss1
      
    # build: node_modules/.bin/electron-builder
    # install: |
    #   mkdir $SNAPCRAFT_PART_INSTALL
    #   mv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL
    prime:
      - -node_modules

apps:
  teams-for-linux:
    command: $SNAP/teams-for-linux
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to
      # ensure libappindicator has readable resources
      TMPDIR: $XDG_RUNTIME_DIR
      # Coerce XDG_CURRENT_DESKTOP to Unity so that App Indicators
      # are used and do not fall back to Notification Area applets
      # or disappear completely.
      XDG_CURRENT_DESKTOP: Unity
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs: 
      - camera
      - network
      - pulseaudio
      - gsettings
      - browser-support
      - home
      - x11
      - unity7
